version: '3.5'
services:

  apigateway:
    image:  capstoneapigateway
    ports:
      - "9001:80"
    

  enquiriesapi:
    image: enquiriesapi
    ports:
      - "5000:80"
    environment:
      Mongo_DB: "mongodb://db:27017"
      DB_NAME: "EnquiryDatabase"
    depends_on:
      - db
      - apigateway

  fitnessprogramsapi:
    image: fitnessprograms
    ports:
      - "5001:80"
    environment:
      Mongo_DB: "mongodb://db:27017"
      DB_NAME: "ProgramDatabase"
    depends_on:
      - db
      - apigateway

  db:
    image: mongo
    ports:
      - "27017:27017"
  
  sqlserverdb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=pass@123
      - ACCEPT_EULA=Y
  
  gymuserapi:
    image: gymuserapi
    ports:
      - "5002:80"
    environment:
      SQL_DB: "Data Source=sqlserverdb;Initial Catalog=UserDB;User Id=sa;Password=pass@123"
    depends_on:
      - sqlserverdb
      - apigateway

  enrollmentsapi:
    image: enrollments
    ports:
      - "9000:80"
    environment:
      SQLEN_DB: "Data Source=sqlserverdb;Initial Catalog=EnrollmentsDB;User Id=sa;Password=pass@123"
    depends_on:
      - sqlserverdb
      - apigateway
