version: '3.5'
services:

  db:
    image: mongo
    ports:
      - "27017:27017"

  sqlserverdb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=pass@123
      - ACCEPT_EULA=Y

  capstoneapigateway:
    image:  capstoneapigateway
    ports:
      - "9001:80"

  enquiriesapi:
    image: enquiriesapi
    ports:
      - "44336:80"
    environment:
      Mongo_DB: "mongodb://db:27017"
      DB_NAME: "EnquiryDatabase"
    depends_on:
      - db
      - capstoneapigateway
    container_name: enquiry-service

  fitnessprogramsapi:
    image: fitnessprograms
    ports:
      - "44344:80"
    environment:
      Mongo_DB: "mongodb://db:27017"
      DB_NAME: "ProgramDatabase"
    depends_on:
      - db
      - apigateway
    container_name: programs-service
  
  gymuserapi:
    image: gymuserapi
    ports:
      - "44317:80"
    environment:
      SQL_DB: "Data Source=sqlserverdb;Initial Catalog=UserDB;User Id=sa;Password=pass@123"
    depends_on:
      - sqlserverdb
      - apigateway
    container_name: user-service

  enrollmentsapi:
    image: enrollments
    ports:
      - "44347:80"
    environment:
      SQLEN_DB: "Data Source=sqlserverdb;Initial Catalog=EnrollmentsDB;User Id=sa;Password=pass@123"
    depends_on:
      - sqlserverdb
      - apigateway
    container_name: enrollment-service